version: 0.0.{build}-{branch}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build_script:
- ps: ./Build $env:APPVEYOR_BUILD_NUMBER $env:APPVEYOR_REPO_BRANCH
artifacts:
- path: '**/*.nuspec'
  name: nuspecs
- path: src/**/*.nupkg
  name: nupkgs
deploy:
- provider: NuGet
  api_key:
    secure: 190gVLa/+blTB/kyPCdv/hY6VIZEscOhotUbycubtqSDQun5/it3BUpeqwuZOxBs
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: 190gVLa/+blTB/kyPCdv/hY6VIZEscOhotUbycubtqSDQun5/it3BUpeqwuZOxBs
  on:
    branch: dev