version: 0.4.100{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}$(PackageSuffix)'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: build.bat
artifacts:
- path: '**/*.nuspec'
  name: nuspecs
- path: src/**/*.nupkg
  name: nupkgs
deploy:
- provider: NuGet
  api_key:
    secure: 190gVLa/+blTB/kyPCdv/hY6VIZEscOhotUbycubtqSDQun5/it3BUpeqwuZOxBs
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: 190gVLa/+blTB/kyPCdv/hY6VIZEscOhotUbycubtqSDQun5/it3BUpeqwuZOxBs
  on:
    branch: dev