//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeGun {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeGun.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;package &gt;
        ///  &lt;metadata&gt;
        ///    &lt;id&gt;{PackageId}&lt;/id&gt;
        ///    &lt;version&gt;{PackageVersion}&lt;/version&gt;
        ///    &lt;title&gt;{PackageTitle}&lt;/title&gt;
        ///    &lt;authors&gt;{Authors}&lt;/authors&gt;
        ///    &lt;owners&gt;{Owners}&lt;/owners&gt;
        ///    &lt;description&gt;{Description}&lt;/description&gt;
        ///    &lt;releaseNotes&gt;{ReleaseNotes}&lt;/releaseNotes&gt;
        ///    &lt;summary&gt;
        ///    &lt;/summary&gt;
        ///    &lt;language&gt;en-US&lt;/language&gt;
        ///    &lt;references&gt;&lt;/references&gt;
        ///    &lt;tags&gt;{Tags}&lt;/tags&gt;
        ///    &lt;dependencies&gt;
        ///{Dependencies}
        ///    &lt;/dependencies&gt;
        ///  &lt;/metadata&gt;
        ///  &lt;files&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NuSpecTemplate {
            get {
                return ResourceManager.GetString("NuSpecTemplate", resourceCulture);
            }
        }
    }
}
